ENT.Type = "anim"
ENT.Base = "ent_damage"
ENT.Category = "Objectives"
ENT.PrintName = "Tea Crate"
ENT.Author = "Iamgoofball"
ENT.StartingHealth = 200
ENT.TeamCheck = 3
ENT.SoundToMake = "physics/glass/glass_bottle_break1.wav"
ENT.UsesTeamIcons = false